# Generated by Django 5.0.6 on 2025-06-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='crime\\static\\img\\logo.jpeg', upload_to='news/')),
                ('is_checked', models.BooleanField(default=False)),
                ('date', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
