# Generated by Django 5.0.6 on 2025-06-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_checked',
        ),
    ]
