# Generated by Django 5.0.6 on 2025-06-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0003_remove_news_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='crime/static/img/logo.jpeg', upload_to='news/'),
        ),
    ]
