# Generated by Django 5.0.6 on 2025-06-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0006_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
