# Generated by Django 5.0.6 on 2025-06-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0008_missingperson_age_missingperson_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('vehicle', 'Vehicle'), ('document', 'Document'), ('jewelry', 'Jewelry'), ('other', 'Other')], max_length=30, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='missing_goods/')),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('found', 'Found'), ('safe', 'Safe')], default='missing', max_length=20)),
                ('last_seen', models.CharField(max_length=200)),
                ('date_reported', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
