# Generated by Django 5.2.3 on 2025-06-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0009_missinggoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missinggoods',
            name='image',
            field=models.ImageField(default='crime/static/img/icon.png', upload_to='missing_goods/'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='image',
            field=models.ImageField(default='crime/static/img/icon.png', upload_to='missing/'),
        ),
    ]
