# Generated by Django 5.2.3 on 2025-07-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0010_alter_missinggoods_image_alter_missingperson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='user_type',
            field=models.CharField(choices=[('investigating_officer', 'Investigating Officer'), ('front_line_officer', 'Front-line Officer')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('Others', 'Others')], max_length=15, null=True),
        ),
    ]
